	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, WATER, GREEN, GREEN
	tilepal 0, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, WATER, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN