	tilepal 0, GRAY, GREEN, WATER, RED, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, GRAY, GREEN, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, BROWN, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, BROWN, BROWN
	tilepal 0, BROWN, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, WATER, ROOF, ROOF, WATER, WATER

rept 32
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, ROOF
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, ROOF
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, RED, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 1, BROWN, BROWN, RED, RED, GREEN, GRAY, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, WATER, WATER, BROWN, BROWN
	tilepal 1, BROWN, BROWN, RED, RED, GREEN, ROOF, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF