	tilepal 0, BROWN, WATER, WATER, WATER, BROWN, BROWN, BROWN, WATER
	tilepal 0, WATER, ROOF, ROOF, BROWN, ROOF, WATER, RED, RED
	tilepal 0, BROWN, WATER, BROWN, BROWN, ROOF, BROWN, BROWN, WATER
	tilepal 0, WATER, ROOF, ROOF, WATER, ROOF, WATER, RED, RED
	tilepal 0, BROWN, BROWN, WATER, BROWN, RED, ROOF, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, ROOF, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, WATER, BROWN, RED, ROOF, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, WATER
	tilepal 0, YELLOW, YELLOW, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, WATER, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER