	tilepal 0, YELLOW, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, GREEN, BROWN, WATER, BROWN, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, WATER, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GREEN, BROWN, GRAY, GRAY, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, WATER, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
